#!/usr/bin/env ruby

require 'd-parse'
require 'pp'

data = <<EOS
first_name,last_name,age
Denis,Defreyne,29
EOS

include DParse::DSL

parser = seq(char('a').repeat, end_of_input)

puts parser.apply('aaab').pretty_message
