#!/usr/bin/env ruby

require 'd-parse'
require 'pp'

data = <<EOS
first_name,last_name,age
Denis,Defreyne,29
EOS

include DParse::DSL

field = repeat(not_chars(',', "\n")).capture
line = field.intersperse(char(',')).select_even
file = seq(line.intersperse(char("\n")).select_even, eof).first

pp file.apply(data)
