#!/usr/bin/env ruby

require 'd-parse'
require 'pp'

data = <<EOS
first_name,last_name,age
Denis,Defreyne,29
EOS

include DParse::DSL

field = repeat(char_not_in([',', "\n"])).capture
line = intersperse(field, char(',')).select_even
file = seq(intersperse(line, char("\n")).select_even, eof).first

pp file.apply(data)
