#!/usr/bin/env ruby

require 'd-parse'
require 'd-parse/dsl'

digit = chars(*('0'..'9')).capture
letter = chars(*('a'..'z')).capture

init = alt(char('d'), char('l')).capture

parser_map = {
  'd' => digit,
  'l' => letter,
}

pair =
  init.bind do |data|
    new_parser = parser_map[data]
    new_parser.map { |d| [data, d] }
  end

parser = pair.repeat

main(parser)
