#!/usr/bin/env ruby

require 'd-parse'
require 'pp'

data = <<EOS
first_name,last_name,age
Denis,Defreyne,29
EOS

include DParse::DSL

parser =
  alt(
    string('Hello!'),
    string('Hello, world!'),
    string('Hello… ?'),
  )

puts parser.apply('Hello, what?').pretty_message
